### ISSUE TITLE
Empty DB

### ISSUE THREAD

**Issue by mohamed265** [Smacrsdv/Faculty-Management-System#2]
@hanysh Our DataBase is Empty
Please Handle this Case in Your Code this reason Produce this Exception
Error creating bean with name 'departmentCourseDetails': Invocation of init method failed; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by mohamed265** [comment]
I Currently Comment the code which produce exception

**Comment by Ahmed-Yehia993** [comment]
the same at DepartmentTeacherAssignation

**Comment by ibrahimali966** [comment]
@hanysh  the same at departmentYearGroups, currently Comment the code which produce exception

**Comment by mohamed265** [comment]
Department Course Also have the Same problem
